username = 'your username here'
client_id = 'your client id here'
client_secret = 'your client secret here'
refresh_token = 'your refresh token here'
geckodriver_executable_path = 'your geckodriver path here'
playlist_name = 'your playlist name here'
